spring.application.name=cineticket_pro

spring.datasource.url=jdbc:postgresql://localhost:5432/cineticket_db
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.expiracao=5
spring.secret= "fadfasfhasdfhasfkuhasdfk"
spring.emissor "joaovgm"